# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalendarius.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 201, 151))
        self.calendarWidget.setSelectedDate(QtCore.QDate(1939, 9, 29))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 16, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 80, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QVideoWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 159, 331, 111))
        self.widget.setObjectName("widget")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(210, 120, 62, 14))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.pushButton_2.setText(_translate("Form", "Stop"))
        self.radioButton.setText(_translate("Form", "Autostart"))
from qvideowidget import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    
    
    
def __init__(self):
    super().__init__()
    self.ui=Ui_MainWindow()
    self.ui.setupUi(self)
    self.media=QMediaPlayer(self)
    self.media.setVideoOutput(self.ui.video)
    vid=QMediaContent(QUrl.fromLocalFile("Video\\7.avi"))
    self.media.set.Media(vid)
    self.media.play()